// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeerProtoBase.proto

package com.game.juhe.server.protobuf.proto;

public final class DeerProtoBase {
  private DeerProtoBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 协议ID
   * </pre>
   *
   * Protobuf enum {@code DeerProtoBase.ProtocolID}
   */
  public enum ProtocolID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PTC_START = 0;</code>
     */
    PTC_START(0),
    /**
     * <pre>
     * 客户端向网关服务器的协议id
     * </pre>
     *
     * <code>PTC_C2S_HeartBeat = 10001;</code>
     */
    PTC_C2S_HeartBeat(10001),
    /**
     * <pre>
     * 网关服务器向客户端的协议id
     * </pre>
     *
     * <code>PTC_S2C_HeartBeat = 10002;</code>
     */
    PTC_S2C_HeartBeat(10002),
    /**
     * <code>PTC_C2G_LOGININFO = 10003;</code>
     */
    PTC_C2G_LOGININFO(10003),
    /**
     * <code>PTC_G2C_ACC_VERIFY_RESULT = 1004;</code>
     */
    PTC_G2C_ACC_VERIFY_RESULT(1004),
    /**
     * <code>PTC_C2S_LOGICLOGIN = 10005;</code>
     */
    PTC_C2S_LOGICLOGIN(10005),
    /**
     * <code>PTC_S2C_LOGICLOIN_RET = 10006;</code>
     */
    PTC_S2C_LOGICLOIN_RET(10006),
    /**
     * <code>PTC_G2C_ROLELIST_RESPONE = 10007;</code>
     */
    PTC_G2C_ROLELIST_RESPONE(10007),
    /**
     * <code>PTC_C2G_GAMELOGIN_REQUEST = 10008;</code>
     */
    PTC_C2G_GAMELOGIN_REQUEST(10008),
    /**
     * <code>PTC_C2G_CREATE_ROLE = 1009;</code>
     */
    PTC_C2G_CREATE_ROLE(1009),
    /**
     * <code>PTC_G2C_CREATEROLE_RESULT = 10010;</code>
     */
    PTC_G2C_CREATEROLE_RESULT(10010),
    /**
     * <code>PTC_G2C_KICKOUTCLIENT = 10011;</code>
     */
    PTC_G2C_KICKOUTCLIENT(10011),
    /**
     * <code>PTC_C2S_EXITACCOUNT = 10012;</code>
     */
    PTC_C2S_EXITACCOUNT(10012),
    /**
     * <code>PTC_C2S_EXITROLE = 10013;</code>
     */
    PTC_C2S_EXITROLE(10013),
    /**
     * <code>PTC_END = 10000;</code>
     */
    PTC_END(10000),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PTC_START = 0;</code>
     */
    public static final int PTC_START_VALUE = 0;
    /**
     * <pre>
     * 客户端向网关服务器的协议id
     * </pre>
     *
     * <code>PTC_C2S_HeartBeat = 10001;</code>
     */
    public static final int PTC_C2S_HeartBeat_VALUE = 10001;
    /**
     * <pre>
     * 网关服务器向客户端的协议id
     * </pre>
     *
     * <code>PTC_S2C_HeartBeat = 10002;</code>
     */
    public static final int PTC_S2C_HeartBeat_VALUE = 10002;
    /**
     * <code>PTC_C2G_LOGININFO = 10003;</code>
     */
    public static final int PTC_C2G_LOGININFO_VALUE = 10003;
    /**
     * <code>PTC_G2C_ACC_VERIFY_RESULT = 1004;</code>
     */
    public static final int PTC_G2C_ACC_VERIFY_RESULT_VALUE = 1004;
    /**
     * <code>PTC_C2S_LOGICLOGIN = 10005;</code>
     */
    public static final int PTC_C2S_LOGICLOGIN_VALUE = 10005;
    /**
     * <code>PTC_S2C_LOGICLOIN_RET = 10006;</code>
     */
    public static final int PTC_S2C_LOGICLOIN_RET_VALUE = 10006;
    /**
     * <code>PTC_G2C_ROLELIST_RESPONE = 10007;</code>
     */
    public static final int PTC_G2C_ROLELIST_RESPONE_VALUE = 10007;
    /**
     * <code>PTC_C2G_GAMELOGIN_REQUEST = 10008;</code>
     */
    public static final int PTC_C2G_GAMELOGIN_REQUEST_VALUE = 10008;
    /**
     * <code>PTC_C2G_CREATE_ROLE = 1009;</code>
     */
    public static final int PTC_C2G_CREATE_ROLE_VALUE = 1009;
    /**
     * <code>PTC_G2C_CREATEROLE_RESULT = 10010;</code>
     */
    public static final int PTC_G2C_CREATEROLE_RESULT_VALUE = 10010;
    /**
     * <code>PTC_G2C_KICKOUTCLIENT = 10011;</code>
     */
    public static final int PTC_G2C_KICKOUTCLIENT_VALUE = 10011;
    /**
     * <code>PTC_C2S_EXITACCOUNT = 10012;</code>
     */
    public static final int PTC_C2S_EXITACCOUNT_VALUE = 10012;
    /**
     * <code>PTC_C2S_EXITROLE = 10013;</code>
     */
    public static final int PTC_C2S_EXITROLE_VALUE = 10013;
    /**
     * <code>PTC_END = 10000;</code>
     */
    public static final int PTC_END_VALUE = 10000;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ProtocolID valueOf(int value) {
      return forNumber(value);
    }

    public static ProtocolID forNumber(int value) {
      switch (value) {
        case 0: return PTC_START;
        case 10001: return PTC_C2S_HeartBeat;
        case 10002: return PTC_S2C_HeartBeat;
        case 10003: return PTC_C2G_LOGININFO;
        case 1004: return PTC_G2C_ACC_VERIFY_RESULT;
        case 10005: return PTC_C2S_LOGICLOGIN;
        case 10006: return PTC_S2C_LOGICLOIN_RET;
        case 10007: return PTC_G2C_ROLELIST_RESPONE;
        case 10008: return PTC_C2G_GAMELOGIN_REQUEST;
        case 1009: return PTC_C2G_CREATE_ROLE;
        case 10010: return PTC_G2C_CREATEROLE_RESULT;
        case 10011: return PTC_G2C_KICKOUTCLIENT;
        case 10012: return PTC_C2S_EXITACCOUNT;
        case 10013: return PTC_C2S_EXITROLE;
        case 10000: return PTC_END;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtocolID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProtocolID> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtocolID>() {
            public ProtocolID findValueByNumber(int number) {
              return ProtocolID.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.juhe.server.protobuf.proto.DeerProtoBase.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProtocolID[] VALUES = values();

    public static ProtocolID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProtocolID(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DeerProtoBase.ProtocolID)
  }

  public interface BGProtocolHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DeerProtoBase.BGProtocolHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 协议号
     * </pre>
     *
     * <code>int32 uProtocolId = 1;</code>
     */
    int getUProtocolId();

    /**
     * <pre>
     * 验证码长度
     * </pre>
     *
     * <code>int32 uKeyLen = 2;</code>
     */
    int getUKeyLen();

    /**
     * <pre>
     *[MAX_SESSIONKEY_LEN=64]
     * </pre>
     *
     * <code>bytes szSessionKey = 3;</code>
     */
    com.google.protobuf.ByteString getSzSessionKey();
  }
  /**
   * <pre>
   * 协议头
   * </pre>
   *
   * Protobuf type {@code DeerProtoBase.BGProtocolHeader}
   */
  public  static final class BGProtocolHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DeerProtoBase.BGProtocolHeader)
      BGProtocolHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BGProtocolHeader.newBuilder() to construct.
    private BGProtocolHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BGProtocolHeader() {
      uProtocolId_ = 0;
      uKeyLen_ = 0;
      szSessionKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BGProtocolHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              uProtocolId_ = input.readInt32();
              break;
            }
            case 16: {

              uKeyLen_ = input.readInt32();
              break;
            }
            case 26: {

              szSessionKey_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.juhe.server.protobuf.proto.DeerProtoBase.internal_static_DeerProtoBase_BGProtocolHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.juhe.server.protobuf.proto.DeerProtoBase.internal_static_DeerProtoBase_BGProtocolHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader.class, com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader.Builder.class);
    }

    public static final int UPROTOCOLID_FIELD_NUMBER = 1;
    private int uProtocolId_;
    /**
     * <pre>
     * 协议号
     * </pre>
     *
     * <code>int32 uProtocolId = 1;</code>
     */
    public int getUProtocolId() {
      return uProtocolId_;
    }

    public static final int UKEYLEN_FIELD_NUMBER = 2;
    private int uKeyLen_;
    /**
     * <pre>
     * 验证码长度
     * </pre>
     *
     * <code>int32 uKeyLen = 2;</code>
     */
    public int getUKeyLen() {
      return uKeyLen_;
    }

    public static final int SZSESSIONKEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString szSessionKey_;
    /**
     * <pre>
     *[MAX_SESSIONKEY_LEN=64]
     * </pre>
     *
     * <code>bytes szSessionKey = 3;</code>
     */
    public com.google.protobuf.ByteString getSzSessionKey() {
      return szSessionKey_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uProtocolId_ != 0) {
        output.writeInt32(1, uProtocolId_);
      }
      if (uKeyLen_ != 0) {
        output.writeInt32(2, uKeyLen_);
      }
      if (!szSessionKey_.isEmpty()) {
        output.writeBytes(3, szSessionKey_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uProtocolId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uProtocolId_);
      }
      if (uKeyLen_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, uKeyLen_);
      }
      if (!szSessionKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, szSessionKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader)) {
        return super.equals(obj);
      }
      com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader other = (com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader) obj;

      boolean result = true;
      result = result && (getUProtocolId()
          == other.getUProtocolId());
      result = result && (getUKeyLen()
          == other.getUKeyLen());
      result = result && getSzSessionKey()
          .equals(other.getSzSessionKey());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UPROTOCOLID_FIELD_NUMBER;
      hash = (53 * hash) + getUProtocolId();
      hash = (37 * hash) + UKEYLEN_FIELD_NUMBER;
      hash = (53 * hash) + getUKeyLen();
      hash = (37 * hash) + SZSESSIONKEY_FIELD_NUMBER;
      hash = (53 * hash) + getSzSessionKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 协议头
     * </pre>
     *
     * Protobuf type {@code DeerProtoBase.BGProtocolHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DeerProtoBase.BGProtocolHeader)
        com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.juhe.server.protobuf.proto.DeerProtoBase.internal_static_DeerProtoBase_BGProtocolHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.juhe.server.protobuf.proto.DeerProtoBase.internal_static_DeerProtoBase_BGProtocolHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader.class, com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader.Builder.class);
      }

      // Construct using com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uProtocolId_ = 0;

        uKeyLen_ = 0;

        szSessionKey_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.juhe.server.protobuf.proto.DeerProtoBase.internal_static_DeerProtoBase_BGProtocolHeader_descriptor;
      }

      @java.lang.Override
      public com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader getDefaultInstanceForType() {
        return com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader build() {
        com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader buildPartial() {
        com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader result = new com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader(this);
        result.uProtocolId_ = uProtocolId_;
        result.uKeyLen_ = uKeyLen_;
        result.szSessionKey_ = szSessionKey_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader) {
          return mergeFrom((com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader other) {
        if (other == com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader.getDefaultInstance()) return this;
        if (other.getUProtocolId() != 0) {
          setUProtocolId(other.getUProtocolId());
        }
        if (other.getUKeyLen() != 0) {
          setUKeyLen(other.getUKeyLen());
        }
        if (other.getSzSessionKey() != com.google.protobuf.ByteString.EMPTY) {
          setSzSessionKey(other.getSzSessionKey());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int uProtocolId_ ;
      /**
       * <pre>
       * 协议号
       * </pre>
       *
       * <code>int32 uProtocolId = 1;</code>
       */
      public int getUProtocolId() {
        return uProtocolId_;
      }
      /**
       * <pre>
       * 协议号
       * </pre>
       *
       * <code>int32 uProtocolId = 1;</code>
       */
      public Builder setUProtocolId(int value) {
        
        uProtocolId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协议号
       * </pre>
       *
       * <code>int32 uProtocolId = 1;</code>
       */
      public Builder clearUProtocolId() {
        
        uProtocolId_ = 0;
        onChanged();
        return this;
      }

      private int uKeyLen_ ;
      /**
       * <pre>
       * 验证码长度
       * </pre>
       *
       * <code>int32 uKeyLen = 2;</code>
       */
      public int getUKeyLen() {
        return uKeyLen_;
      }
      /**
       * <pre>
       * 验证码长度
       * </pre>
       *
       * <code>int32 uKeyLen = 2;</code>
       */
      public Builder setUKeyLen(int value) {
        
        uKeyLen_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 验证码长度
       * </pre>
       *
       * <code>int32 uKeyLen = 2;</code>
       */
      public Builder clearUKeyLen() {
        
        uKeyLen_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString szSessionKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *[MAX_SESSIONKEY_LEN=64]
       * </pre>
       *
       * <code>bytes szSessionKey = 3;</code>
       */
      public com.google.protobuf.ByteString getSzSessionKey() {
        return szSessionKey_;
      }
      /**
       * <pre>
       *[MAX_SESSIONKEY_LEN=64]
       * </pre>
       *
       * <code>bytes szSessionKey = 3;</code>
       */
      public Builder setSzSessionKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        szSessionKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *[MAX_SESSIONKEY_LEN=64]
       * </pre>
       *
       * <code>bytes szSessionKey = 3;</code>
       */
      public Builder clearSzSessionKey() {
        
        szSessionKey_ = getDefaultInstance().getSzSessionKey();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DeerProtoBase.BGProtocolHeader)
    }

    // @@protoc_insertion_point(class_scope:DeerProtoBase.BGProtocolHeader)
    private static final com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader();
    }

    public static com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BGProtocolHeader>
        PARSER = new com.google.protobuf.AbstractParser<BGProtocolHeader>() {
      @java.lang.Override
      public BGProtocolHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BGProtocolHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BGProtocolHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BGProtocolHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.juhe.server.protobuf.proto.DeerProtoBase.BGProtocolHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeerProtoBase_BGProtocolHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeerProtoBase_BGProtocolHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023DeerProtoBase.proto\022\rDeerProtoBase\"N\n\020" +
      "BGProtocolHeader\022\023\n\013uProtocolId\030\001 \001(\005\022\017\n" +
      "\007uKeyLen\030\002 \001(\005\022\024\n\014szSessionKey\030\003 \001(\014*\214\003\n" +
      "\nProtocolID\022\r\n\tPTC_START\020\000\022\026\n\021PTC_C2S_He" +
      "artBeat\020\221N\022\026\n\021PTC_S2C_HeartBeat\020\222N\022\026\n\021PT" +
      "C_C2G_LOGININFO\020\223N\022\036\n\031PTC_G2C_ACC_VERIFY" +
      "_RESULT\020\354\007\022\027\n\022PTC_C2S_LOGICLOGIN\020\225N\022\032\n\025P" +
      "TC_S2C_LOGICLOIN_RET\020\226N\022\035\n\030PTC_G2C_ROLEL" +
      "IST_RESPONE\020\227N\022\036\n\031PTC_C2G_GAMELOGIN_REQU" +
      "EST\020\230N\022\030\n\023PTC_C2G_CREATE_ROLE\020\361\007\022\036\n\031PTC_" +
      "G2C_CREATEROLE_RESULT\020\232N\022\032\n\025PTC_G2C_KICK" +
      "OUTCLIENT\020\233N\022\030\n\023PTC_C2S_EXITACCOUNT\020\234N\022\025" +
      "\n\020PTC_C2S_EXITROLE\020\235N\022\014\n\007PTC_END\020\220NB%\n#c" +
      "om.game.juhe.server.protobuf.protob\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DeerProtoBase_BGProtocolHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DeerProtoBase_BGProtocolHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeerProtoBase_BGProtocolHeader_descriptor,
        new java.lang.String[] { "UProtocolId", "UKeyLen", "SzSessionKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
