// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeerGameBase.proto

package com.game.juhe.server.protobuf.proto;

public final class DeerGameBase {
  private DeerGameBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code DeerGameBase.PacketType}
   */
  public enum PacketType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Undefined = 0;</code>
     */
    Undefined(0),
    /**
     * <code>ClientToServer = 1;</code>
     */
    ClientToServer(1),
    /**
     * <code>ServerToClient = 2;</code>
     */
    ServerToClient(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Undefined = 0;</code>
     */
    public static final int Undefined_VALUE = 0;
    /**
     * <code>ClientToServer = 1;</code>
     */
    public static final int ClientToServer_VALUE = 1;
    /**
     * <code>ServerToClient = 2;</code>
     */
    public static final int ServerToClient_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PacketType valueOf(int value) {
      return forNumber(value);
    }

    public static PacketType forNumber(int value) {
      switch (value) {
        case 0: return Undefined;
        case 1: return ClientToServer;
        case 2: return ServerToClient;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PacketType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PacketType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PacketType>() {
            public PacketType findValueByNumber(int number) {
              return PacketType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.juhe.server.protobuf.proto.DeerGameBase.getDescriptor().getEnumTypes().get(0);
    }

    private static final PacketType[] VALUES = values();

    public static PacketType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PacketType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DeerGameBase.PacketType)
  }

  public interface PacketHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DeerGameBase.PacketHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.DeerGameBase.PacketType packetType = 1;</code>
     */
    int getPacketTypeValue();
    /**
     * <code>.DeerGameBase.PacketType packetType = 1;</code>
     */
    com.game.juhe.server.protobuf.proto.DeerGameBase.PacketType getPacketType();

    /**
     * <code>int64 id = 2;</code>
     */
    long getId();

    /**
     * <code>int64 packetLength = 3;</code>
     */
    long getPacketLength();

    /**
     * <code>bool isValid = 4;</code>
     */
    boolean getIsValid();
  }
  /**
   * Protobuf type {@code DeerGameBase.PacketHeader}
   */
  public  static final class PacketHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DeerGameBase.PacketHeader)
      PacketHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PacketHeader.newBuilder() to construct.
    private PacketHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PacketHeader() {
      packetType_ = 0;
      id_ = 0L;
      packetLength_ = 0L;
      isValid_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PacketHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              packetType_ = rawValue;
              break;
            }
            case 16: {

              id_ = input.readInt64();
              break;
            }
            case 24: {

              packetLength_ = input.readInt64();
              break;
            }
            case 32: {

              isValid_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_PacketHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_PacketHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader.class, com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader.Builder.class);
    }

    public static final int PACKETTYPE_FIELD_NUMBER = 1;
    private int packetType_;
    /**
     * <code>.DeerGameBase.PacketType packetType = 1;</code>
     */
    public int getPacketTypeValue() {
      return packetType_;
    }
    /**
     * <code>.DeerGameBase.PacketType packetType = 1;</code>
     */
    public com.game.juhe.server.protobuf.proto.DeerGameBase.PacketType getPacketType() {
      @SuppressWarnings("deprecation")
      com.game.juhe.server.protobuf.proto.DeerGameBase.PacketType result = com.game.juhe.server.protobuf.proto.DeerGameBase.PacketType.valueOf(packetType_);
      return result == null ? com.game.juhe.server.protobuf.proto.DeerGameBase.PacketType.UNRECOGNIZED : result;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <code>int64 id = 2;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int PACKETLENGTH_FIELD_NUMBER = 3;
    private long packetLength_;
    /**
     * <code>int64 packetLength = 3;</code>
     */
    public long getPacketLength() {
      return packetLength_;
    }

    public static final int ISVALID_FIELD_NUMBER = 4;
    private boolean isValid_;
    /**
     * <code>bool isValid = 4;</code>
     */
    public boolean getIsValid() {
      return isValid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (packetType_ != com.game.juhe.server.protobuf.proto.DeerGameBase.PacketType.Undefined.getNumber()) {
        output.writeEnum(1, packetType_);
      }
      if (id_ != 0L) {
        output.writeInt64(2, id_);
      }
      if (packetLength_ != 0L) {
        output.writeInt64(3, packetLength_);
      }
      if (isValid_ != false) {
        output.writeBool(4, isValid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (packetType_ != com.game.juhe.server.protobuf.proto.DeerGameBase.PacketType.Undefined.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, packetType_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (packetLength_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, packetLength_);
      }
      if (isValid_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isValid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader)) {
        return super.equals(obj);
      }
      com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader other = (com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader) obj;

      boolean result = true;
      result = result && packetType_ == other.packetType_;
      result = result && (getId()
          == other.getId());
      result = result && (getPacketLength()
          == other.getPacketLength());
      result = result && (getIsValid()
          == other.getIsValid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PACKETTYPE_FIELD_NUMBER;
      hash = (53 * hash) + packetType_;
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + PACKETLENGTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPacketLength());
      hash = (37 * hash) + ISVALID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsValid());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DeerGameBase.PacketHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DeerGameBase.PacketHeader)
        com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_PacketHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_PacketHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader.class, com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader.Builder.class);
      }

      // Construct using com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        packetType_ = 0;

        id_ = 0L;

        packetLength_ = 0L;

        isValid_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_PacketHeader_descriptor;
      }

      @java.lang.Override
      public com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader getDefaultInstanceForType() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader build() {
        com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader buildPartial() {
        com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader result = new com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader(this);
        result.packetType_ = packetType_;
        result.id_ = id_;
        result.packetLength_ = packetLength_;
        result.isValid_ = isValid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader) {
          return mergeFrom((com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader other) {
        if (other == com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader.getDefaultInstance()) return this;
        if (other.packetType_ != 0) {
          setPacketTypeValue(other.getPacketTypeValue());
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getPacketLength() != 0L) {
          setPacketLength(other.getPacketLength());
        }
        if (other.getIsValid() != false) {
          setIsValid(other.getIsValid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int packetType_ = 0;
      /**
       * <code>.DeerGameBase.PacketType packetType = 1;</code>
       */
      public int getPacketTypeValue() {
        return packetType_;
      }
      /**
       * <code>.DeerGameBase.PacketType packetType = 1;</code>
       */
      public Builder setPacketTypeValue(int value) {
        packetType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.DeerGameBase.PacketType packetType = 1;</code>
       */
      public com.game.juhe.server.protobuf.proto.DeerGameBase.PacketType getPacketType() {
        @SuppressWarnings("deprecation")
        com.game.juhe.server.protobuf.proto.DeerGameBase.PacketType result = com.game.juhe.server.protobuf.proto.DeerGameBase.PacketType.valueOf(packetType_);
        return result == null ? com.game.juhe.server.protobuf.proto.DeerGameBase.PacketType.UNRECOGNIZED : result;
      }
      /**
       * <code>.DeerGameBase.PacketType packetType = 1;</code>
       */
      public Builder setPacketType(com.game.juhe.server.protobuf.proto.DeerGameBase.PacketType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        packetType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.DeerGameBase.PacketType packetType = 1;</code>
       */
      public Builder clearPacketType() {
        
        packetType_ = 0;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 2;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 2;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long packetLength_ ;
      /**
       * <code>int64 packetLength = 3;</code>
       */
      public long getPacketLength() {
        return packetLength_;
      }
      /**
       * <code>int64 packetLength = 3;</code>
       */
      public Builder setPacketLength(long value) {
        
        packetLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 packetLength = 3;</code>
       */
      public Builder clearPacketLength() {
        
        packetLength_ = 0L;
        onChanged();
        return this;
      }

      private boolean isValid_ ;
      /**
       * <code>bool isValid = 4;</code>
       */
      public boolean getIsValid() {
        return isValid_;
      }
      /**
       * <code>bool isValid = 4;</code>
       */
      public Builder setIsValid(boolean value) {
        
        isValid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isValid = 4;</code>
       */
      public Builder clearIsValid() {
        
        isValid_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DeerGameBase.PacketHeader)
    }

    // @@protoc_insertion_point(class_scope:DeerGameBase.PacketHeader)
    private static final com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader();
    }

    public static com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PacketHeader>
        PARSER = new com.google.protobuf.AbstractParser<PacketHeader>() {
      @java.lang.Override
      public PacketHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PacketHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PacketHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PacketHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.juhe.server.protobuf.proto.DeerGameBase.PacketHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CSHeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DeerGameBase.CSHeartBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 dwTime = 1;</code>
     */
    long getDwTime();
  }
  /**
   * <pre>
   * PTC_C2S_HeartBeat
   * </pre>
   *
   * Protobuf type {@code DeerGameBase.CSHeartBeat}
   */
  public  static final class CSHeartBeat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DeerGameBase.CSHeartBeat)
      CSHeartBeatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CSHeartBeat.newBuilder() to construct.
    private CSHeartBeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CSHeartBeat() {
      dwTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CSHeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              dwTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_CSHeartBeat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_CSHeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat.class, com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat.Builder.class);
    }

    public static final int DWTIME_FIELD_NUMBER = 1;
    private long dwTime_;
    /**
     * <code>int64 dwTime = 1;</code>
     */
    public long getDwTime() {
      return dwTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dwTime_ != 0L) {
        output.writeInt64(1, dwTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dwTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, dwTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat)) {
        return super.equals(obj);
      }
      com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat other = (com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat) obj;

      boolean result = true;
      result = result && (getDwTime()
          == other.getDwTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DWTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDwTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * PTC_C2S_HeartBeat
     * </pre>
     *
     * Protobuf type {@code DeerGameBase.CSHeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DeerGameBase.CSHeartBeat)
        com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_CSHeartBeat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_CSHeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat.class, com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat.Builder.class);
      }

      // Construct using com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dwTime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_CSHeartBeat_descriptor;
      }

      @java.lang.Override
      public com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat getDefaultInstanceForType() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat build() {
        com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat buildPartial() {
        com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat result = new com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat(this);
        result.dwTime_ = dwTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat) {
          return mergeFrom((com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat other) {
        if (other == com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat.getDefaultInstance()) return this;
        if (other.getDwTime() != 0L) {
          setDwTime(other.getDwTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long dwTime_ ;
      /**
       * <code>int64 dwTime = 1;</code>
       */
      public long getDwTime() {
        return dwTime_;
      }
      /**
       * <code>int64 dwTime = 1;</code>
       */
      public Builder setDwTime(long value) {
        
        dwTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 dwTime = 1;</code>
       */
      public Builder clearDwTime() {
        
        dwTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DeerGameBase.CSHeartBeat)
    }

    // @@protoc_insertion_point(class_scope:DeerGameBase.CSHeartBeat)
    private static final com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat();
    }

    public static com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CSHeartBeat>
        PARSER = new com.google.protobuf.AbstractParser<CSHeartBeat>() {
      @java.lang.Override
      public CSHeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSHeartBeat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CSHeartBeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSHeartBeat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.juhe.server.protobuf.proto.DeerGameBase.CSHeartBeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SCHeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DeerGameBase.SCHeartBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 dwTime = 1;</code>
     */
    long getDwTime();
  }
  /**
   * <pre>
   * PTC_S2C_HeartBeat
   * </pre>
   *
   * Protobuf type {@code DeerGameBase.SCHeartBeat}
   */
  public  static final class SCHeartBeat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DeerGameBase.SCHeartBeat)
      SCHeartBeatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SCHeartBeat.newBuilder() to construct.
    private SCHeartBeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SCHeartBeat() {
      dwTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SCHeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              dwTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_SCHeartBeat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_SCHeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat.class, com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat.Builder.class);
    }

    public static final int DWTIME_FIELD_NUMBER = 1;
    private long dwTime_;
    /**
     * <code>int64 dwTime = 1;</code>
     */
    public long getDwTime() {
      return dwTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dwTime_ != 0L) {
        output.writeInt64(1, dwTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dwTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, dwTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat)) {
        return super.equals(obj);
      }
      com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat other = (com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat) obj;

      boolean result = true;
      result = result && (getDwTime()
          == other.getDwTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DWTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDwTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * PTC_S2C_HeartBeat
     * </pre>
     *
     * Protobuf type {@code DeerGameBase.SCHeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DeerGameBase.SCHeartBeat)
        com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_SCHeartBeat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_SCHeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat.class, com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat.Builder.class);
      }

      // Construct using com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dwTime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_SCHeartBeat_descriptor;
      }

      @java.lang.Override
      public com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat getDefaultInstanceForType() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat build() {
        com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat buildPartial() {
        com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat result = new com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat(this);
        result.dwTime_ = dwTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat) {
          return mergeFrom((com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat other) {
        if (other == com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat.getDefaultInstance()) return this;
        if (other.getDwTime() != 0L) {
          setDwTime(other.getDwTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long dwTime_ ;
      /**
       * <code>int64 dwTime = 1;</code>
       */
      public long getDwTime() {
        return dwTime_;
      }
      /**
       * <code>int64 dwTime = 1;</code>
       */
      public Builder setDwTime(long value) {
        
        dwTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 dwTime = 1;</code>
       */
      public Builder clearDwTime() {
        
        dwTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DeerGameBase.SCHeartBeat)
    }

    // @@protoc_insertion_point(class_scope:DeerGameBase.SCHeartBeat)
    private static final com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat();
    }

    public static com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SCHeartBeat>
        PARSER = new com.google.protobuf.AbstractParser<SCHeartBeat>() {
      @java.lang.Override
      public SCHeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SCHeartBeat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SCHeartBeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SCHeartBeat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.juhe.server.protobuf.proto.DeerGameBase.SCHeartBeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DPRoleBaseInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DeerGameBase.DPRoleBaseInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * guid
     * </pre>
     *
     * <code>uint64 ullRoleGuid = 1;</code>
     */
    long getUllRoleGuid();

    /**
     * <pre>
     * 角色名    
     * </pre>
     *
     * <code>string szRoleName = 2;</code>
     */
    java.lang.String getSzRoleName();
    /**
     * <pre>
     * 角色名    
     * </pre>
     *
     * <code>string szRoleName = 2;</code>
     */
    com.google.protobuf.ByteString
        getSzRoleNameBytes();

    /**
     * <pre>
     * 角色等级
     * </pre>
     *
     * <code>int32 nLevel = 3;</code>
     */
    int getNLevel();

    /**
     * <pre>
     * 角色ID
     * </pre>
     *
     * <code>int32 nProfessionId = 4;</code>
     */
    int getNProfessionId();

    /**
     * <pre>
     * 头像
     * </pre>
     *
     * <code>int32 nPortraitId = 5;</code>
     */
    int getNPortraitId();

    /**
     * <pre>
     * 战斗力
     * </pre>
     *
     * <code>int32 nFightPower = 6;</code>
     */
    int getNFightPower();

    /**
     * <pre>
     * 时装ID       
     * </pre>
     *
     * <code>int32 nClothId = 7;</code>
     */
    int getNClothId();
  }
  /**
   * <pre>
   * 玩家角色基础数据数据
   * </pre>
   *
   * Protobuf type {@code DeerGameBase.DPRoleBaseInfo}
   */
  public  static final class DPRoleBaseInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DeerGameBase.DPRoleBaseInfo)
      DPRoleBaseInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DPRoleBaseInfo.newBuilder() to construct.
    private DPRoleBaseInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DPRoleBaseInfo() {
      ullRoleGuid_ = 0L;
      szRoleName_ = "";
      nLevel_ = 0;
      nProfessionId_ = 0;
      nPortraitId_ = 0;
      nFightPower_ = 0;
      nClothId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DPRoleBaseInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              ullRoleGuid_ = input.readUInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              szRoleName_ = s;
              break;
            }
            case 24: {

              nLevel_ = input.readInt32();
              break;
            }
            case 32: {

              nProfessionId_ = input.readInt32();
              break;
            }
            case 40: {

              nPortraitId_ = input.readInt32();
              break;
            }
            case 48: {

              nFightPower_ = input.readInt32();
              break;
            }
            case 56: {

              nClothId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_DPRoleBaseInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_DPRoleBaseInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo.class, com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo.Builder.class);
    }

    public static final int ULLROLEGUID_FIELD_NUMBER = 1;
    private long ullRoleGuid_;
    /**
     * <pre>
     * guid
     * </pre>
     *
     * <code>uint64 ullRoleGuid = 1;</code>
     */
    public long getUllRoleGuid() {
      return ullRoleGuid_;
    }

    public static final int SZROLENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object szRoleName_;
    /**
     * <pre>
     * 角色名    
     * </pre>
     *
     * <code>string szRoleName = 2;</code>
     */
    public java.lang.String getSzRoleName() {
      java.lang.Object ref = szRoleName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        szRoleName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 角色名    
     * </pre>
     *
     * <code>string szRoleName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSzRoleNameBytes() {
      java.lang.Object ref = szRoleName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        szRoleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NLEVEL_FIELD_NUMBER = 3;
    private int nLevel_;
    /**
     * <pre>
     * 角色等级
     * </pre>
     *
     * <code>int32 nLevel = 3;</code>
     */
    public int getNLevel() {
      return nLevel_;
    }

    public static final int NPROFESSIONID_FIELD_NUMBER = 4;
    private int nProfessionId_;
    /**
     * <pre>
     * 角色ID
     * </pre>
     *
     * <code>int32 nProfessionId = 4;</code>
     */
    public int getNProfessionId() {
      return nProfessionId_;
    }

    public static final int NPORTRAITID_FIELD_NUMBER = 5;
    private int nPortraitId_;
    /**
     * <pre>
     * 头像
     * </pre>
     *
     * <code>int32 nPortraitId = 5;</code>
     */
    public int getNPortraitId() {
      return nPortraitId_;
    }

    public static final int NFIGHTPOWER_FIELD_NUMBER = 6;
    private int nFightPower_;
    /**
     * <pre>
     * 战斗力
     * </pre>
     *
     * <code>int32 nFightPower = 6;</code>
     */
    public int getNFightPower() {
      return nFightPower_;
    }

    public static final int NCLOTHID_FIELD_NUMBER = 7;
    private int nClothId_;
    /**
     * <pre>
     * 时装ID       
     * </pre>
     *
     * <code>int32 nClothId = 7;</code>
     */
    public int getNClothId() {
      return nClothId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ullRoleGuid_ != 0L) {
        output.writeUInt64(1, ullRoleGuid_);
      }
      if (!getSzRoleNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, szRoleName_);
      }
      if (nLevel_ != 0) {
        output.writeInt32(3, nLevel_);
      }
      if (nProfessionId_ != 0) {
        output.writeInt32(4, nProfessionId_);
      }
      if (nPortraitId_ != 0) {
        output.writeInt32(5, nPortraitId_);
      }
      if (nFightPower_ != 0) {
        output.writeInt32(6, nFightPower_);
      }
      if (nClothId_ != 0) {
        output.writeInt32(7, nClothId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ullRoleGuid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, ullRoleGuid_);
      }
      if (!getSzRoleNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, szRoleName_);
      }
      if (nLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, nLevel_);
      }
      if (nProfessionId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, nProfessionId_);
      }
      if (nPortraitId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, nPortraitId_);
      }
      if (nFightPower_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, nFightPower_);
      }
      if (nClothId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, nClothId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo)) {
        return super.equals(obj);
      }
      com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo other = (com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo) obj;

      boolean result = true;
      result = result && (getUllRoleGuid()
          == other.getUllRoleGuid());
      result = result && getSzRoleName()
          .equals(other.getSzRoleName());
      result = result && (getNLevel()
          == other.getNLevel());
      result = result && (getNProfessionId()
          == other.getNProfessionId());
      result = result && (getNPortraitId()
          == other.getNPortraitId());
      result = result && (getNFightPower()
          == other.getNFightPower());
      result = result && (getNClothId()
          == other.getNClothId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ULLROLEGUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUllRoleGuid());
      hash = (37 * hash) + SZROLENAME_FIELD_NUMBER;
      hash = (53 * hash) + getSzRoleName().hashCode();
      hash = (37 * hash) + NLEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getNLevel();
      hash = (37 * hash) + NPROFESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getNProfessionId();
      hash = (37 * hash) + NPORTRAITID_FIELD_NUMBER;
      hash = (53 * hash) + getNPortraitId();
      hash = (37 * hash) + NFIGHTPOWER_FIELD_NUMBER;
      hash = (53 * hash) + getNFightPower();
      hash = (37 * hash) + NCLOTHID_FIELD_NUMBER;
      hash = (53 * hash) + getNClothId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 玩家角色基础数据数据
     * </pre>
     *
     * Protobuf type {@code DeerGameBase.DPRoleBaseInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DeerGameBase.DPRoleBaseInfo)
        com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_DPRoleBaseInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_DPRoleBaseInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo.class, com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo.Builder.class);
      }

      // Construct using com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ullRoleGuid_ = 0L;

        szRoleName_ = "";

        nLevel_ = 0;

        nProfessionId_ = 0;

        nPortraitId_ = 0;

        nFightPower_ = 0;

        nClothId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.internal_static_DeerGameBase_DPRoleBaseInfo_descriptor;
      }

      @java.lang.Override
      public com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo getDefaultInstanceForType() {
        return com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo build() {
        com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo buildPartial() {
        com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo result = new com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo(this);
        result.ullRoleGuid_ = ullRoleGuid_;
        result.szRoleName_ = szRoleName_;
        result.nLevel_ = nLevel_;
        result.nProfessionId_ = nProfessionId_;
        result.nPortraitId_ = nPortraitId_;
        result.nFightPower_ = nFightPower_;
        result.nClothId_ = nClothId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo) {
          return mergeFrom((com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo other) {
        if (other == com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo.getDefaultInstance()) return this;
        if (other.getUllRoleGuid() != 0L) {
          setUllRoleGuid(other.getUllRoleGuid());
        }
        if (!other.getSzRoleName().isEmpty()) {
          szRoleName_ = other.szRoleName_;
          onChanged();
        }
        if (other.getNLevel() != 0) {
          setNLevel(other.getNLevel());
        }
        if (other.getNProfessionId() != 0) {
          setNProfessionId(other.getNProfessionId());
        }
        if (other.getNPortraitId() != 0) {
          setNPortraitId(other.getNPortraitId());
        }
        if (other.getNFightPower() != 0) {
          setNFightPower(other.getNFightPower());
        }
        if (other.getNClothId() != 0) {
          setNClothId(other.getNClothId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long ullRoleGuid_ ;
      /**
       * <pre>
       * guid
       * </pre>
       *
       * <code>uint64 ullRoleGuid = 1;</code>
       */
      public long getUllRoleGuid() {
        return ullRoleGuid_;
      }
      /**
       * <pre>
       * guid
       * </pre>
       *
       * <code>uint64 ullRoleGuid = 1;</code>
       */
      public Builder setUllRoleGuid(long value) {
        
        ullRoleGuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * guid
       * </pre>
       *
       * <code>uint64 ullRoleGuid = 1;</code>
       */
      public Builder clearUllRoleGuid() {
        
        ullRoleGuid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object szRoleName_ = "";
      /**
       * <pre>
       * 角色名    
       * </pre>
       *
       * <code>string szRoleName = 2;</code>
       */
      public java.lang.String getSzRoleName() {
        java.lang.Object ref = szRoleName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          szRoleName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 角色名    
       * </pre>
       *
       * <code>string szRoleName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSzRoleNameBytes() {
        java.lang.Object ref = szRoleName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          szRoleName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 角色名    
       * </pre>
       *
       * <code>string szRoleName = 2;</code>
       */
      public Builder setSzRoleName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        szRoleName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 角色名    
       * </pre>
       *
       * <code>string szRoleName = 2;</code>
       */
      public Builder clearSzRoleName() {
        
        szRoleName_ = getDefaultInstance().getSzRoleName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 角色名    
       * </pre>
       *
       * <code>string szRoleName = 2;</code>
       */
      public Builder setSzRoleNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        szRoleName_ = value;
        onChanged();
        return this;
      }

      private int nLevel_ ;
      /**
       * <pre>
       * 角色等级
       * </pre>
       *
       * <code>int32 nLevel = 3;</code>
       */
      public int getNLevel() {
        return nLevel_;
      }
      /**
       * <pre>
       * 角色等级
       * </pre>
       *
       * <code>int32 nLevel = 3;</code>
       */
      public Builder setNLevel(int value) {
        
        nLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 角色等级
       * </pre>
       *
       * <code>int32 nLevel = 3;</code>
       */
      public Builder clearNLevel() {
        
        nLevel_ = 0;
        onChanged();
        return this;
      }

      private int nProfessionId_ ;
      /**
       * <pre>
       * 角色ID
       * </pre>
       *
       * <code>int32 nProfessionId = 4;</code>
       */
      public int getNProfessionId() {
        return nProfessionId_;
      }
      /**
       * <pre>
       * 角色ID
       * </pre>
       *
       * <code>int32 nProfessionId = 4;</code>
       */
      public Builder setNProfessionId(int value) {
        
        nProfessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 角色ID
       * </pre>
       *
       * <code>int32 nProfessionId = 4;</code>
       */
      public Builder clearNProfessionId() {
        
        nProfessionId_ = 0;
        onChanged();
        return this;
      }

      private int nPortraitId_ ;
      /**
       * <pre>
       * 头像
       * </pre>
       *
       * <code>int32 nPortraitId = 5;</code>
       */
      public int getNPortraitId() {
        return nPortraitId_;
      }
      /**
       * <pre>
       * 头像
       * </pre>
       *
       * <code>int32 nPortraitId = 5;</code>
       */
      public Builder setNPortraitId(int value) {
        
        nPortraitId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 头像
       * </pre>
       *
       * <code>int32 nPortraitId = 5;</code>
       */
      public Builder clearNPortraitId() {
        
        nPortraitId_ = 0;
        onChanged();
        return this;
      }

      private int nFightPower_ ;
      /**
       * <pre>
       * 战斗力
       * </pre>
       *
       * <code>int32 nFightPower = 6;</code>
       */
      public int getNFightPower() {
        return nFightPower_;
      }
      /**
       * <pre>
       * 战斗力
       * </pre>
       *
       * <code>int32 nFightPower = 6;</code>
       */
      public Builder setNFightPower(int value) {
        
        nFightPower_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 战斗力
       * </pre>
       *
       * <code>int32 nFightPower = 6;</code>
       */
      public Builder clearNFightPower() {
        
        nFightPower_ = 0;
        onChanged();
        return this;
      }

      private int nClothId_ ;
      /**
       * <pre>
       * 时装ID       
       * </pre>
       *
       * <code>int32 nClothId = 7;</code>
       */
      public int getNClothId() {
        return nClothId_;
      }
      /**
       * <pre>
       * 时装ID       
       * </pre>
       *
       * <code>int32 nClothId = 7;</code>
       */
      public Builder setNClothId(int value) {
        
        nClothId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时装ID       
       * </pre>
       *
       * <code>int32 nClothId = 7;</code>
       */
      public Builder clearNClothId() {
        
        nClothId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DeerGameBase.DPRoleBaseInfo)
    }

    // @@protoc_insertion_point(class_scope:DeerGameBase.DPRoleBaseInfo)
    private static final com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo();
    }

    public static com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DPRoleBaseInfo>
        PARSER = new com.google.protobuf.AbstractParser<DPRoleBaseInfo>() {
      @java.lang.Override
      public DPRoleBaseInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DPRoleBaseInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DPRoleBaseInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DPRoleBaseInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.juhe.server.protobuf.proto.DeerGameBase.DPRoleBaseInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeerGameBase_PacketHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeerGameBase_PacketHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeerGameBase_CSHeartBeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeerGameBase_CSHeartBeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeerGameBase_SCHeartBeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeerGameBase_SCHeartBeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeerGameBase_DPRoleBaseInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeerGameBase_DPRoleBaseInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022DeerGameBase.proto\022\014DeerGameBase\"o\n\014Pa" +
      "cketHeader\022,\n\npacketType\030\001 \001(\0162\030.DeerGam" +
      "eBase.PacketType\022\n\n\002id\030\002 \001(\003\022\024\n\014packetLe" +
      "ngth\030\003 \001(\003\022\017\n\007isValid\030\004 \001(\010\"\035\n\013CSHeartBe" +
      "at\022\016\n\006dwTime\030\001 \001(\003\"\035\n\013SCHeartBeat\022\016\n\006dwT" +
      "ime\030\001 \001(\003\"\234\001\n\016DPRoleBaseInfo\022\023\n\013ullRoleG" +
      "uid\030\001 \001(\004\022\022\n\nszRoleName\030\002 \001(\t\022\016\n\006nLevel\030" +
      "\003 \001(\005\022\025\n\rnProfessionId\030\004 \001(\005\022\023\n\013nPortrai" +
      "tId\030\005 \001(\005\022\023\n\013nFightPower\030\006 \001(\005\022\020\n\010nCloth" +
      "Id\030\007 \001(\005*C\n\nPacketType\022\r\n\tUndefined\020\000\022\022\n" +
      "\016ClientToServer\020\001\022\022\n\016ServerToClient\020\002B%\n" +
      "#com.game.juhe.server.protobuf.protob\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DeerGameBase_PacketHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DeerGameBase_PacketHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeerGameBase_PacketHeader_descriptor,
        new java.lang.String[] { "PacketType", "Id", "PacketLength", "IsValid", });
    internal_static_DeerGameBase_CSHeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DeerGameBase_CSHeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeerGameBase_CSHeartBeat_descriptor,
        new java.lang.String[] { "DwTime", });
    internal_static_DeerGameBase_SCHeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DeerGameBase_SCHeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeerGameBase_SCHeartBeat_descriptor,
        new java.lang.String[] { "DwTime", });
    internal_static_DeerGameBase_DPRoleBaseInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DeerGameBase_DPRoleBaseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeerGameBase_DPRoleBaseInfo_descriptor,
        new java.lang.String[] { "UllRoleGuid", "SzRoleName", "NLevel", "NProfessionId", "NPortraitId", "NFightPower", "NClothId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
